server {
    # 1. Listen on port 443 (HTTPS) only
    listen 443 ssl;
    listen [::]:443 ssl;

    # 2. Your Domain Name (Hardcoded for stability)
    server_name mboughra.42.fr www.mboughra.42.fr;

    # 3. SSL Certificates
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # 4. Root directory
    root /var/www/html;
    index index.php index.html;

    # 5. Handle PHP files
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}